# -*- coding: utf-8 -*-
"""COSC 419 Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uDTOFEpgxzSUh9N5Uw6QjWweQMcdkdNh

##Step 0: Simply check runtime parameters & GPU
"""

# First, check your runtime environment
import torch
import sys

print(f"Python version: {sys.version}")
print(f"PyTorch version: {torch.__version__}")
print(f"CUDA available: {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"CUDA version: {torch.version.cuda}")

# Restart runtime if you just installed packages
# Runtime → Restart runtime (or click the restart button)

"""## Step 1: Download Soccernet 2023 Data & Setup Directory
1. create `soccernet_jersey\` directory sturcture
2. download the soccer jersey data
3. extract and organise the data
4. download the models
    - Scene text recognition `PARSeq` model
    - Legibility classification model `resnet34`


"""

# 📦 SoccerNet Jersey-2023 — Google Colab Setup (Minimal)
# ✅ Only: directory setup + dataset download + model downloads
# ❌ No git repos, no conda envs, no extra dependencies beyond SoccerNet+gdown

import os
import sys
import shutil
import urllib.request
from pathlib import Path
import zipfile

# =============================================================================
# CONFIGURATION (Simplified for Colab)
# =============================================================================
class Config:
    project_root = Path("/content/soccernet_jersey")
    data_task = "jersey-2023"
    splits = ["train", "test"]

    dataset = {
        'SoccerNet': {
            'root_dir': './data',
            'test': {
                'images': 'test/images',
                'gt': 'test/test_gt.json',
            },
            'val': {
                'images': 'val/images',
                'gt': 'val/val_gt.json',
            },
            'train': {
                'images': 'train/images',
                'gt': 'train/train_gt.json',
            },
            # Model paths & Google Drive URLs (trimmed)
            'legibility_model': "models/legibility_resnet34_soccer_20240215.pth",
            'legibility_model_url': "https://drive.google.com/uc?id=18HAuZbge3z8TSfRiX_FzsnKgiBs-RRNw",
            'pose_model_url': 'https://drive.google.com/uc?id=1A3ftF118IcxMn_QONndR-8dPWpf7XzdV',
            'str_model': 'models/parseq_epoch=24-step=2575-val_accuracy=95.6044-val_NED=96.3255.ckpt',
            'str_model_url': "https://drive.google.com/uc?id=1uRln22tlhneVt3P6MePmVxBWSLMsL3bm",
        }
    }

cfg = Config()

# =============================================================================
# UTILITIES
# =============================================================================
def ensure_dir(path):
    Path(path).mkdir(parents=True, exist_ok=True)
    return Path(path)

def download_file_gdrive(url, save_path, description=""):
    """Download from Google Drive using gdown."""
    print(f"⬇️  {description or save_path}")
    try:
        import gdown
        gdown.download(url, str(save_path), quiet=False)
        print(f"✅ Saved to {save_path}")
        return True
    except Exception as e:
        print(f"❌ Failed: {e}")
        # Fallback: try direct urllib (won't work for GDrive but worth a shot)
        try:
            urllib.request.urlretrieve(url.strip(), str(save_path))
            print(f"✅ Saved via fallback to {save_path}")
            return True
        except:
            return False

# =============================================================================
# STEP 1: Setup Directory Structure
# =============================================================================
print("🔧 STEP 1: Creating project structure...")
root = cfg.project_root
ensure_dir(root)
ensure_dir(root / "data")
ensure_dir(root / "models")
ensure_dir(root / "out")
ensure_dir(root / "scripts")
print(f"✅ Project root: {root}")

# =============================================================================
# STEP 2: Install minimal dependencies (SoccerNet + gdown)
# =============================================================================
print("\n📦 STEP 2: Installing SoccerNet + gdown...")
!pip install -q SoccerNet gdown
print("✅ Dependencies installed")

# =============================================================================
# STEP 3: Download SoccerNet Jersey-2023 Dataset
# =============================================================================
print(f"\n🌐 STEP 3: Downloading SoccerNet task: {cfg.data_task}")
print(f"   Splits: {cfg.splits}")

from SoccerNet.Downloader import SoccerNetDownloader as SNdl

sn_data_root = root / "data" / "SoccerNet"
ensure_dir(sn_data_root)

mySNdl = SNdl(LocalDirectory=str(sn_data_root))

try:
    mySNdl.downloadDataTask(task=cfg.data_task, split=cfg.splits)
    print("✅ Dataset download complete")
except Exception as e:
    print(f"⚠️  Download issue: {e}")
    print("💡 Tip: Re-run this cell if connection drops")

# =============================================================================
# STEP 4: Extract & Organize Dataset
# =============================================================================
print(f"\n🗂️  STEP 4: Extracting zip files...")

zip_dir = root / "data" / "SoccerNet" / cfg.data_task

for split in cfg.splits:
    zip_path = zip_dir / f"{split}.zip"
    dest_dir = root / "data" / split

    if not zip_path.exists():
        print(f"⚠️  {zip_path.name} not found — skipping {split}")
        continue

    ensure_dir(dest_dir)
    print(f"📦 Extracting {split}.zip → {dest_dir}/")

    try:
        with zipfile.ZipFile(zip_path, 'r') as zip_ref:
            zip_ref.extractall(dest_dir)
        print(f"✅ Extracted {split}")
    except Exception as e:
        print(f"❌ Failed to extract {split}: {e}")

# =============================================================================
# STEP 5: Fix Nested Directory Structure (common issue)
# =============================================================================
print(f"\n🔧 STEP 5: Fixing nested directory structure...")

for split in cfg.splits:
    split_dir = root / "data" / split
    nested_dir = split_dir / split  # e.g., data/train/train/

    if nested_dir.exists() and nested_dir.is_dir():
        print(f"🔁 Fixing {split} nesting...")
        for item in nested_dir.iterdir():
            target = split_dir / item.name
            if not target.exists():
                shutil.move(str(item), str(split_dir))
            elif item.is_dir() and target.is_dir():
                # Merge directories
                for subitem in item.iterdir():
                    shutil.move(str(subitem), str(target / subitem.name))
                item.rmdir()
        try:
            nested_dir.rmdir()
            print(f"   ✅ Cleaned up nested folder")
        except OSError:
            pass  # Directory not empty, that's ok

print("✅ Directory structure fixed")

# =============================================================================
# STEP 6: Download Model Weights
# =============================================================================
print(f"\n🤖 STEP 6: Downloading model weights...")

sn_cfg = cfg.dataset['SoccerNet']
models_downloaded = 0

# Pose model (ViTPose checkpoint)
pose_ckpt = root / "pose" / "checkpoints" / "vitpose-h.pth"
ensure_dir(pose_ckpt.parent)
if not pose_ckpt.exists():
    if download_file_gdrive(sn_cfg['pose_model_url'], pose_ckpt, "ViTPose checkpoint"):
        models_downloaded += 1
else:
    print(f"✅ Pose model already exists")

# STR model (PARSeq)
if 'str_model_url' in sn_cfg and 'str_model' in sn_cfg:
    str_path = root / sn_cfg['str_model']
    ensure_dir(str_path.parent)
    if not str_path.exists():
        if download_file_gdrive(sn_cfg['str_model_url'], str_path, "STR (PARSeq) model"):
            models_downloaded += 1
    else:
        print(f"✅ STR model already exists")

# Legibility model
if 'legibility_model_url' in sn_cfg and 'legibility_model' in sn_cfg:
    leg_path = root / sn_cfg['legibility_model']
    ensure_dir(leg_path.parent)
    if not leg_path.exists():
        if download_file_gdrive(sn_cfg['legibility_model_url'], leg_path, "Legibility model"):
            models_downloaded += 1
    else:
        print(f"✅ Legibility model already exists")

print(f"\n✅ Downloaded {models_downloaded}/3 model(s)")

# =============================================================================
# STEP 7: Verify & Summary
# =============================================================================
print(f"\n{'='*60}")
print("🎉 SETUP COMPLETE (Colab Minimal)")
print(f"{'='*60}")
print(f"📁 Project: {root}")
print(f"📊 Data:    {root / 'data'}")
print(f"🤖 Models:  {root / 'models'}")

print(f"\n📋 Dataset splits:")
for split in cfg.splits:
    img_dir = root / "data" / split / "images"
    count = len([d for d in img_dir.iterdir() if d.is_dir()]) if img_dir.exists() else 0
    print(f"   • {split:10s}: {count} tracklets")

print(f"\n🔑 Model paths:")
print(f"   • STR:        {sn_cfg['str_model']}")
print(f"   • Legibility: {sn_cfg['legibility_model']}")
print(f"   • Pose:       pose/checkpoints/vitpose-h.pth")

print(f"\n🚀 Next: Mount your code or start training!")
print(f"💡 Quick check:")
print(f"   ```python")
print(f"   from pathlib import Path")
print(f"   data = Path('/content/soccernet_jersey/data')")
print(f"   print(f'Train tracklets: {{len(list((data/'train'/'images').iterdir()))}}')")
print(f"   ```")
print(f"{'='*60}")

"""## Step 2: Downlaod NAFnet and set-up NAFnet model

### 2.1: Download NAFNet git repo
https://github.com/megvii-research/NAFNet
"""

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/megvii-research/NAFNet
# %cd NAFNet

"""### 2.2: set-up requirements"""

!pip install -r requirements.txt
!pip install --upgrade --no-cache-dir gdown
!python3 setup.py develop --no_cuda_ext

"""### 2.3: Download pretrained NAFNEt models for dnoising,debluring, and super resolution enhancement



"""

#denoising:
import gdown
gdown.download('https://drive.google.com/uc?id=14Fht1QQJ2gMlk4N1ERCRuElg8JfjrWWR', "./experiments/pretrained_models/", quiet=False)

#debluring:
import gdown
gdown.download('https://drive.google.com/uc?id=14D4V4raNYIOhETfcuuLI3bGLB-OYIv6X', "./experiments/pretrained_models/", quiet=False)

#super-resolution:
!gdown https://drive.google.com/uc?id=1TIdQhPtBrZb2wrBdAp9l8NHINLeExOwb -O ./experiments/pretrained_models/
!gdown https://drive.google.com/drive/folders/1zWedm3Q6_6pxTql881DR6xe-v9SPUe70?usp=sharing --folder

from google.colab import drive
drive.mount('/content/drive')

"""### 2.4: Preperation code to be able to call NAFNet models"""

# Common preparation for all restoration tasks
import torch
import numpy as np
import cv2
import matplotlib.pyplot as plt

from basicsr.models import create_model
from basicsr.utils import img2tensor as _img2tensor, tensor2img, imwrite
from basicsr.utils.options import parse

# Common utility functions
def imread(img_path):
    """Read image and convert BGR to RGB"""
    img = cv2.imread(img_path)

    # NEW STEP
    # img = crop_torso(img)

    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    return img

def img2tensor(img, bgr2rgb=False, float32=True):
    """Convert numpy image to tensor"""
    img = img.astype(np.float32) / 255.
    return _img2tensor(img, bgr2rgb=bgr2rgb, float32=float32)

def single_image_inference(model, img, save_path):
    """Run inference for single image tasks (denoising, deblurring)"""
    model.feed_data(data={'lq': img.unsqueeze(dim=0)})

    if model.opt['val'].get('grids', False):
        model.grids()

    model.test()

    if model.opt['val'].get('grids', False):
        model.grids_inverse()

    visuals = model.get_current_visuals()
    sr_img = tensor2img([visuals['result']])
    imwrite(sr_img, save_path)

def display_single(img1, img2, title1='Input image', title2='NAFNet output'):
    """Display comparison for single image tasks"""
    fig = plt.figure(figsize=(25, 10))
    ax1 = fig.add_subplot(1, 2, 1)
    plt.title(title1, fontsize=16)
    ax1.axis('off')
    ax2 = fig.add_subplot(1, 2, 2)
    plt.title(title2, fontsize=16)
    ax2.axis('off')
    ax1.imshow(img1)
    ax2.imshow(img2)

# Super resolution specific functions
def display_stereo(LR_l, LR_r, SR_l, SR_r,
                   title1='Input image (Left)', title2='NAFSSR output (Left)',
                   title3='Input image (Right)', title4='NAFSSR output (Right)'):
    """Display comparison for stereo super resolution"""
    h, w = SR_l.shape[:2]
    LR_l = cv2.resize(LR_l, (w, h), interpolation=cv2.INTER_CUBIC)
    LR_r = cv2.resize(LR_r, (w, h), interpolation=cv2.INTER_CUBIC)

    fig = plt.figure(figsize=(w//40, h//40))
    ax1 = fig.add_subplot(2, 2, 1)
    plt.title(title1, fontsize=16)
    ax1.axis('off')
    ax2 = fig.add_subplot(2, 2, 2)
    plt.title(title2, fontsize=16)
    ax2.axis('off')
    ax1.imshow(LR_l)
    ax2.imshow(SR_l)

    ax3 = fig.add_subplot(2, 2, 3)
    plt.title(title3, fontsize=16)
    ax3.axis('off')
    ax4 = fig.add_subplot(2, 2, 4)
    plt.title(title4, fontsize=16)
    ax4.axis('off')
    ax3.imshow(LR_r)
    ax4.imshow(SR_r)

    plt.subplots_adjust(wspace=0.04, hspace=0.04)

def stereo_image_inference(model, img_l, img_r, save_path):
    """Run inference for stereo super resolution"""
    img = torch.cat([img_l, img_r], dim=0)
    model.feed_data(data={'lq': img.unsqueeze(dim=0)})

    if model.opt['val'].get('grids', False):
        model.grids()

    model.test()

    if model.opt['val'].get('grids', False):
        model.grids_inverse()

    visuals = model.get_current_visuals()
    img_L = visuals['result'][:,:3]
    img_R = visuals['result'][:,3:]
    img_L, img_R = tensor2img([img_L, img_R])

    imwrite(img_L, save_path.format('L'))
    imwrite(img_R, save_path.format('R'))

# Optional: Export commonly used functions for convenience
__all__ = [
    'imread', 'img2tensor', 'single_image_inference', 'display_single',
    'display_stereo', 'stereo_image_inference',
    'torch', 'np', 'cv2', 'plt',  # Libraries
    'create_model', 'parse'  # BasicSR utilities
]

"""### 2.5: Create/Instantiate the NAFNet pretrained models"""

#denoise:
opt_path = 'options/test/SIDD/NAFNet-width64.yml'
opt = parse(opt_path, is_train=False)
opt['dist'] = False
NAFNet_dn = create_model(opt)

#deblur:
opt_path = 'options/test/REDS/NAFNet-width64.yml'
opt = parse(opt_path, is_train=False)
opt['dist'] = False
NAFNet_db = create_model(opt)

#super res:
opt_path = 'options/test/NAFSSR/NAFSSR-L_4x.yml'
opt = parse(opt_path, is_train=False)
opt['dist'] = False
NAFSSR = create_model(opt)

"""---
## 2.Optional: Testing
feel free to edit these cells to test the NAFnet ability
however please edit the input path to an exisitng image that you upload somehow
"""

#test
input_path = '/content/7_399.jpg'
output_path_dn = '/content/denoised.png'
output_path_db = '/content/deblurred.png'

from PIL import Image

# Load original image
img_original = Image.open(input_path)

# Zoom/scale up by multiplying dimensions (e.g., 2x larger)
scale_factor = 2  # Change this: 2 = 2x larger, 3 = 3x larger, etc.
new_size = (img_original.width * scale_factor, img_original.height * scale_factor)
img_input = img_original.resize(new_size, Image.LANCZOS)  # High-quality upscale

img_input.save('/content/input_converted.png', 'PNG')
img_input = imread('/content/input_converted.png')

# Prepare input tensor
inp = img2tensor(img_input)

# Run NAFNet_dn (Denoising)
single_image_inference(NAFNet_dn, inp, output_path_dn)
img_output_dn = imread(output_path_dn)

# Run NAFNet_db (Deblurring)
single_image_inference(NAFNet_db, inp, output_path_db)
img_output_db = imread(output_path_db)

# Display: Original (scaled), Denoised, Deblurred
print(f"📐 Original: {img_original.width}x{img_original.height} → Scaled: {img_input.shape[1]}x{img_input.shape[0]}")
display(img_input, img_output_dn, img_output_db)

input_path_l = '/content/deblurred.png'
input_path_r = '/content/deblurred.png'
output_path = '/content/Middlebury_sr_x4_sword2_{}.png'

from PIL import Image


# Convert to PNG
input_path_l_png = '/content/deblurred.png'
input_path_r_png = '/content/deblurred.png'

Image.open(input_path_l).convert('RGB').save(input_path_l_png, 'PNG')
Image.open(input_path_r).convert('RGB').save(input_path_r_png, 'PNG')

# Now use the PNG paths
img_input_l = imread(input_path_l_png)
img_input_r = imread(input_path_r_png)



img_l = imread(input_path_l)
inp_l = img2tensor(img_l)
img_r = imread(input_path_r)
inp_r = img2tensor(img_r)
stereo_image_inference(NAFSSR, inp_l, inp_r, output_path)
SR_l = imread(output_path.format('L'))
SR_r = imread(output_path.format('R'))
display(img_l, img_r, SR_l, SR_r)

"""---

## Step 3:Legibility Classifier
This cell defines a **complete legibility classification library** setup

### 1. **Configuration**
- Sets thresholds for blur, brightness, contrast, and jersey size
- Defines weights for combining multiple quality metrics
- Stores paths to pre-trained models

### 2. **Heuristic Classifier** (`HeuristicLegibilityClassifier`)
- **Image quality metrics**:
  - Blur score (Laplacian variance)
  - Brightness (mean pixel value)
  - Contrast (standard deviation)
  - Jersey size ratio (from edge detection)
  - Text region detection (via contour analysis)
- Combines metrics with weighted scoring
- Classifies as: LEGIBLE, BLURRY, DARK, BRIGHT, OCCLUDED, SMALL, UNKNOWN

### 3. **ML Classifier** (`MLLegibilityClassifier`)
- Uses ResNet34 fine-tuned for binary legibility classification
- Loads pre-trained weights from the SoccerNet model
- Applies ImageNet normalization transforms
- Returns probability score (0-1)

### 4. **Main Pipeline** (`LegibilityClassifierPipeline`)
- Auto-selects between ML and heuristic backends
- Can process:
  - Single images
  - Tracklets (sequences of jersey images)
  - Full datasets of tracklets
- Features:
  - Filtering to keep only legible frames
  - JSON result export
  - Tracklet-level statistics
  - Progress bars (tqdm)
  - GPU/CPU auto-detection

This library is designed to **filter out low-quality jersey images** before feeding them to downstream tasks like number recognition, improving overall accuracy and runtime.
"""

# 🔧 Cell 1: Legibility Classifier Library
# Run this ONCE at the start of your Colab session

import os, sys, json, warnings, math
from pathlib import Path
from typing import Dict, List, Tuple, Optional, Union, Any
from datetime import datetime
from collections import defaultdict
from enum import Enum

import numpy as np
import torch
import torch.nn as nn
from torchvision import models, transforms
from PIL import Image
from tqdm.notebook import tqdm  # Colab-friendly progress bars
import cv2

warnings.filterwarnings('ignore')

# ============================================================================
# CONFIGURATION
# ============================================================================
class Config:
    DEFAULT_MODEL = Path("/content/soccernet_jersey/models/legibility_resnet34_soccer_20240215.pth")
    BLUR_THRESHOLD = 150.0
    MIN_BRIGHTNESS = 40.0
    MAX_BRIGHTNESS = 210.0
    MIN_CONTRAST = 30.0
    MIN_JERSEY_SIZE = 80
    MIN_SCORE_THRESHOLD = 0.50
    WEIGHT_BLUR = 0.30
    WEIGHT_BRIGHTNESS = 0.15
    WEIGHT_CONTRAST = 0.25
    WEIGHT_SIZE = 0.20
    TEXT_BONUS = 0.10
    IMAGE_SIZE = 224
    IMAGENET_MEAN = [0.485, 0.456, 0.406]
    IMAGENET_STD = [0.229, 0.224, 0.225]

# ============================================================================
# UTILITIES
# ============================================================================
def convert_to_serializable(obj: Any) -> Any:
    if isinstance(obj, dict):
        return {k: convert_to_serializable(v) for k, v in obj.items()}
    elif isinstance(obj, (list, tuple)):
        return [convert_to_serializable(v) for v in obj]
    elif isinstance(obj, np.ndarray):
        return obj.tolist()
    elif isinstance(obj, (np.integer, np.floating, np.bool_)):
        return obj.item()
    elif isinstance(obj, torch.Tensor):
        return obj.cpu().detach().numpy().tolist()
    elif isinstance(obj, Enum):
        return obj.value
    elif isinstance(obj, (Path, os.PathLike)):
        return str(obj)
    return obj

def get_device(verbose: bool = True) -> str:
    if not torch.cuda.is_available():
        return 'cpu'
    try:
        import torchvision
        test_boxes = torch.tensor([[0.0, 0.0, 10.0, 10.0]], dtype=torch.float32, device='cuda')
        test_scores = torch.tensor([0.9], dtype=torch.float32, device='cuda')
        torchvision.ops.nms(test_boxes, test_scores, 0.5)
        if verbose:
            print(f"🎮 GPU: {torch.cuda.get_device_name(0)}")
        return 'cuda'
    except:
        if verbose:
            print("⚠ CUDA incompatible, using CPU")
        return 'cpu'

# ============================================================================
# ENUM
# ============================================================================
class LegibilityStatus(Enum):
    LEGIBLE = "legible"
    BLURRY = "blurry"
    DARK = "dark"
    BRIGHT = "bright"
    OCCLUDED = "occluded"
    SMALL = "small"
    UNKNOWN = "unknown"

# ============================================================================
# HEURISTIC CLASSIFIER
# ============================================================================
class HeuristicLegibilityClassifier:
    def __init__(self, verbose: bool = True, **kwargs):
        self.verbose = verbose
        self.blur_threshold = kwargs.get('blur_threshold', Config.BLUR_THRESHOLD)
        self.min_brightness = kwargs.get('min_brightness', Config.MIN_BRIGHTNESS)
        self.max_brightness = kwargs.get('max_brightness', Config.MAX_BRIGHTNESS)
        self.min_contrast = kwargs.get('min_contrast', Config.MIN_CONTRAST)
        self.min_score_threshold = kwargs.get('min_score_threshold', Config.MIN_SCORE_THRESHOLD)
        self.score_history = []
        if verbose:
            print(f"📏 Heuristic thresholds initialized")

    def classify(self, img_path: Union[str, Path]) -> Dict[str, Any]:
        try:
            img = cv2.imread(str(img_path))
            if img is None:
                return self._error_result(str(img_path), "Could not read image")
            gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
            blur_score = cv2.Laplacian(gray, cv2.CV_64F).var()
            brightness = np.mean(gray)
            contrast = np.std(gray)
            edges = cv2.Canny(gray, 50, 150)
            jersey_size = np.sum(edges > 0) / edges.size * 100
            has_text = self._detect_text_regions(gray)
            score = self._calculate_score(blur_score, brightness, contrast, jersey_size, has_text)
            self.score_history.append(score)
            status, legible = self._determine_status(blur_score, brightness, contrast, jersey_size, score)
            return {
                'image': str(img_path), 'legible': bool(legible), 'status': status.value,
                'score': float(score),
                'metrics': {'blur_score': float(blur_score), 'brightness': float(brightness),
                           'contrast': float(contrast), 'jersey_size_ratio': float(jersey_size),
                           'has_text_region': bool(has_text)}
            }
        except Exception as e:
            return self._error_result(str(img_path), str(e))

    def _error_result(self, img_path: str, error: str) -> Dict[str, Any]:
        return {'image': img_path, 'legible': False, 'status': LegibilityStatus.UNKNOWN.value,
                'score': 0.0, 'metrics': {}, 'error': error}

    def _detect_text_regions(self, gray: np.ndarray) -> bool:
        try:
            thresh = cv2.adaptiveThreshold(gray, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C,
                                          cv2.THRESH_BINARY_INV, 11, 2)
            kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (3, 3))
            eroded = cv2.erode(cv2.dilate(thresh, kernel, iterations=2), kernel, iterations=1)
            contours, _ = cv2.findContours(eroded, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
            img_area = gray.size
            for contour in contours:
                area = cv2.contourArea(contour)
                if 50 < area < img_area * 0.15:
                    x, y, w, h = cv2.boundingRect(contour)
                    if 0.3 < w / float(h) < 3.0:
                        return True
            return False
        except:
            return False

    def _calculate_score(self, blur: float, brightness: float, contrast: float,
                        jersey_size: float, has_text: bool) -> float:
        blur_norm = min(blur / self.blur_threshold, 1.0)
        brightness_norm = max(0.0, min(1.0, 1.0 - abs(brightness - 127.5) / 127.5))
        contrast_norm = min(contrast / 60.0, 1.0)
        size_norm = min(jersey_size / 10.0, 1.0)
        return min(1.0, (Config.WEIGHT_BLUR * blur_norm + Config.WEIGHT_BRIGHTNESS * brightness_norm +
                        Config.WEIGHT_CONTRAST * contrast_norm + Config.WEIGHT_SIZE * size_norm +
                        (Config.TEXT_BONUS if has_text else 0.0)))

    def _determine_status(self, blur: float, brightness: float, contrast: float,
                         jersey_size: float, score: float) -> Tuple[LegibilityStatus, bool]:
        if blur < self.blur_threshold * 0.4:
            return LegibilityStatus.BLURRY, False
        if brightness < self.min_brightness:
            return LegibilityStatus.DARK, False
        if brightness > self.max_brightness:
            return LegibilityStatus.BRIGHT, False
        if contrast < self.min_contrast:
            return LegibilityStatus.OCCLUDED, False
        if jersey_size < 3.0:
            return LegibilityStatus.SMALL, False
        legible = score >= self.min_score_threshold
        return (LegibilityStatus.LEGIBLE if legible else LegibilityStatus.UNKNOWN), bool(legible)

    def get_score_statistics(self) -> Dict[str, float]:
        if not self.score_history:
            return {}
        scores = np.array(self.score_history)
        return {'mean': float(np.mean(scores)), 'median': float(np.median(scores)),
                'std': float(np.std(scores)), 'min': float(np.min(scores)),
                'max': float(np.max(scores)), 'count': len(scores)}

# ============================================================================
# ML CLASSIFIER
# ============================================================================
class LegibilityClassifier34(nn.Module):
    def __init__(self, num_classes: int = 1, pretrained: bool = True):
        super().__init__()
        self.backbone = models.resnet34(weights=models.ResNet34_Weights.IMAGENET1K_V1 if pretrained else None)
        self.backbone.fc = nn.Linear(self.backbone.fc.in_features, num_classes)
    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return torch.sigmoid(self.backbone(x))

class MLLegibilityClassifier:
    def __init__(self, model_path: str, device: str = 'cpu', threshold: float = 0.5, verbose: bool = True):
        self.device = device
        self.threshold = threshold
        self.verbose = verbose
        checkpoint_info = self._inspect_checkpoint(model_path)
        self.model = self._load_model(model_path, checkpoint_info).to(device).eval()
        self.transform = transforms.Compose([
            transforms.Resize((Config.IMAGE_SIZE, Config.IMAGE_SIZE)),
            transforms.ToTensor(),
            transforms.Normalize(mean=Config.IMAGENET_MEAN, std=Config.IMAGENET_STD)
        ])
        if verbose:
            print(f"🎯 ML Backend Ready (ResNet34) on {device}")

    def _inspect_checkpoint(self, model_path: str) -> Dict[str, Any]:
        try:
            checkpoint = torch.load(model_path, map_location='cpu', weights_only=False)
            state_dict = checkpoint.get('model_state_dict', checkpoint.get('state_dict', checkpoint))
            keys = list(state_dict.keys())
            prefixes = set(k.split('.')[0] for k in keys if '.' in k)
            return {'state_dict': state_dict, 'total_keys': len(keys), 'prefixes': list(prefixes), 'sample_keys': keys[:5]}
        except Exception as e:
            return {'state_dict': None, 'total_keys': 0, 'prefixes': [], 'sample_keys': [], 'error': str(e)}

    def _load_model(self, model_path: str, checkpoint_info: Dict[str, Any]) -> nn.Module:
        try:
            model = LegibilityClassifier34(pretrained=True)
            model_state = model.state_dict()
            state_dict = checkpoint_info['state_dict']
            new_state_dict = {}
            for key, value in state_dict.items():
                for possible_key in [key, key.replace('model_ft.', 'backbone.'), key.replace('model.', 'backbone.'),
                                    f'backbone.{key}' if not any(key.startswith(p) for p in ['model_ft.', 'model.', 'backbone.']) else key]:
                    if possible_key in model_state:
                        new_state_dict[possible_key] = value
                        break
            model.load_state_dict(new_state_dict, strict=False)
            return model
        except Exception as e:
            if self.verbose:
                print(f"⚠ Error loading model: {e}, falling back to CPU")
            self.device = 'cpu'
            model = LegibilityClassifier34(pretrained=True)
            if checkpoint_info['state_dict']:
                model.load_state_dict(checkpoint_info['state_dict'], strict=False)
            return model

    def classify(self, img_path: Union[str, Path]) -> Dict[str, Any]:
        try:
            img_tensor = self.transform(Image.open(str(img_path)).convert('RGB')).unsqueeze(0).to(self.device)
            with torch.no_grad():
                score = float(self.model(img_tensor).item())
            legible = bool(score >= self.threshold)
            return {'image': str(img_path), 'legible': legible,
                   'status': (LegibilityStatus.LEGIBLE if legible else LegibilityStatus.UNKNOWN).value,
                   'score': score, 'metrics': {'model_score': score}}
        except Exception as e:
            return {'image': str(img_path), 'legible': False, 'status': LegibilityStatus.UNKNOWN.value,
                   'score': 0.0, 'metrics': {}, 'error': str(e)}

# ============================================================================
# MAIN PIPELINE (Colab-Friendly)
# ============================================================================
class LegibilityClassifierPipeline:
    def __init__(self, backend: str = 'auto', model_path: Optional[str] = None,
                 device: Optional[str] = None, threshold: float = 0.5, verbose: bool = True, strict_mode: bool = False):
        self.verbose = verbose
        self.threshold = threshold
        self.strict_mode = strict_mode
        self.device = device or get_device(verbose)
        if backend == 'auto':
            backend = 'ml' if model_path and Path(model_path).exists() else 'heuristic'
        if backend == 'ml' and model_path and Path(model_path).exists():
            try:
                self.classifier = MLLegibilityClassifier(model_path, self.device, threshold, verbose)
                self.backend = 'ml'
            except Exception as e:
                if verbose:
                    print(f"⚠ ML backend failed: {e}, falling back to heuristic")
                self.classifier = HeuristicLegibilityClassifier(verbose=verbose)
                self.backend = 'heuristic'
        else:
            params = {'blur_threshold': 200.0, 'min_brightness': 50.0, 'max_brightness': 200.0,
                     'min_contrast': 40.0, 'min_score_threshold': 0.55} if strict_mode else {}
            self.classifier = HeuristicLegibilityClassifier(verbose=verbose, **params)
            self.backend = 'heuristic'
        if verbose:
            print(f"🔧 Legibility Classifier Ready (Backend: {self.backend}, Device: {self.device})")

    def classify_image(self, img_path: Union[str, Path]) -> Dict[str, Any]:
        return self.classifier.classify(img_path)

    def process_tracklet(self, tracklet_dir: Union[str, Path], filter_legible: bool = True) -> Tuple[List[Dict], List[str]]:
        tracklet_path = Path(tracklet_dir)
        if not tracklet_path.is_dir():
            raise NotADirectoryError(f"Tracklet directory not found: {tracklet_path}")
        image_paths = sorted([f for f in tracklet_path.iterdir()
                             if f.suffix.lower() in {'.jpg', '.jpeg', '.png', '.bmp'} and f.is_file()])
        results, kept = [], []
        for img_path in tqdm(image_paths, desc=f"Legibility: {tracklet_path.name}", disable=not self.verbose):
            result = self.classify_image(img_path)
            results.append(result)
            if not filter_legible or result['legible']:
                kept.append(str(img_path))
        return results, kept

    def process_dataset(self, tracklets_folder: Union[str, Path], output_folder: Optional[Union[str, Path]] = None,
                       save_results: bool = True, filter_legible: bool = True, max_tracklets: Optional[int] = None) -> Dict[str, Any]:
        tracklets_path = Path(tracklets_folder)
        if not tracklets_path.is_dir():
            raise NotADirectoryError(f"Tracklets folder not found: {tracklets_path}")
        tracklets = sorted([d for d in tracklets_path.iterdir() if d.is_dir() and not d.name.startswith('.')])
        if not tracklets:
            return {"processed": 0, "total_frames": 0, "legible_frames": 0}
        if max_tracklets:
            tracklets = tracklets[:max_tracklets]
        output_path = Path(output_folder) if output_folder and save_results else None
        if output_path:
            output_path.mkdir(parents=True, exist_ok=True)
        stats = {"processed": 0, "total_frames": 0, "legible_frames": 0, "filtered_frames": 0,
                "failed_tracklets": 0, "status_counts": defaultdict(int), "tracklet_stats": {},
                "backend": self.backend, "device": self.device, "threshold": self.threshold,
                "filter_legible": filter_legible, "strict_mode": self.strict_mode,
                "timestamp": datetime.now().isoformat()}
        for tracklet in tqdm(tracklets, desc="Processing tracklets", disable=not self.verbose):
            try:
                results, kept = self.process_tracklet(tracklet, filter_legible=filter_legible)
                if not results:
                    stats["failed_tracklets"] += 1
                    continue
                for result in results:
                    stats["status_counts"][result['status']] += 1
                    if result['legible']:
                        stats["legible_frames"] += 1
                stats["total_frames"] += len(results)
                stats["filtered_frames"] += len(kept)
                if output_path and save_results:
                    with open(output_path / f"{tracklet.name}_legibility.json", 'w') as f:
                        json.dump(convert_to_serializable(results), f, indent=2)
                    if filter_legible:
                        with open(output_path / f"{tracklet.name}_kept_images.txt", 'w') as f:
                            f.write('\n'.join(kept))
                stats["processed"] += 1
                stats["tracklet_stats"][tracklet.name] = {
                    "total_frames": len(results), "legible_frames": len(kept),
                    "legibility_ratio": len(kept) / len(results) if results else 0
                }
            except Exception as e:
                print(f"✗ Error processing {tracklet.name}: {e}")
                stats["failed_tracklets"] += 1
        stats["status_counts"] = dict(stats["status_counts"])
        if self.verbose and stats["total_frames"] > 0:
            legible_pct = stats['legible_frames'] / stats['total_frames'] * 100
            print(f"\n✅ Complete: {stats['legible_frames']}/{stats['total_frames']} legible ({legible_pct:.1f}%)")
        return stats

    def cleanup(self):
        if self.verbose:
            print("🧹 Cleaned up")

print("✅ Legibility classifier library loaded!")

"""---
### 4.Optional test legibility classifier
edit `CONFIG` for different results
"""

# ⚙️ Cell 2: Run Legibility Classifier (Adjust Parameters Below)
# Modify the CONFIG section, then run this cell

# ==================== 🔧 CONFIGURATION ====================
CONFIG = {
    # Paths
    'tracklets_folder': '/content/soccernet_jersey/data/train/images',
    'output_folder': '/content/soccernet_jersey/out/legibility_results',
    'model_path': '/content/soccernet_jersey/models/legibility_resnet34_soccer_20240215.pth',

    # Backend selection: 'auto', 'heuristic', or 'ml'
    'backend': 'auto',

    # Classification threshold (0.0–1.0): higher = stricter
    'threshold': 0.85,

    # Limit processing (set None for all)
    'max_tracklets': 15,  # Try 1-10 for testing, None for full dataset

    # Filtering options
    'filter_legible': True,   # Only keep legible frames in output list
    'save_results': True,     # Save JSON results to output_folder
    'strict_mode': False,     # Use stricter heuristic thresholds

    # Device: 'cuda', 'cpu', or None (auto-detect)
    'device': None,

    # Verbosity
    'verbose': True,
}

# ==================== 🚀 EXECUTION ====================
print("🔍 Loading configuration...")
for k, v in CONFIG.items():
    print(f"   • {k:20s}: {v}")

print(f"\n🔧 Initializing pipeline...")
pipeline = LegibilityClassifierPipeline(
    backend=CONFIG['backend'],
    model_path=CONFIG['model_path'],
    device=CONFIG['device'],
    threshold=CONFIG['threshold'],
    verbose=CONFIG['verbose'],
    strict_mode=CONFIG['strict_mode']
)

try:
    print(f"\n📁 Processing: {CONFIG['tracklets_folder']}")
    stats = pipeline.process_dataset(
        tracklets_folder=CONFIG['tracklets_folder'],
        output_folder=CONFIG['output_folder'] if CONFIG['save_results'] else None,
        save_results=CONFIG['save_results'],
        filter_legible=CONFIG['filter_legible'],
        max_tracklets=CONFIG['max_tracklets']
    )

    # 📊 Display Summary
    print(f"\n{'='*60}")
    print("📈 RESULTS SUMMARY")
    print(f"{'='*60}")
    print(f"Backend:        {stats['backend']}")
    print(f"Device:         {stats['device']}")
    print(f"Threshold:      {stats['threshold']}")
    print(f"Tracklets:      {stats['processed']} processed, {stats['failed_tracklets']} failed")
    print(f"Total frames:   {stats['total_frames']}")
    print(f"Legible frames: {stats['legible_frames']} ({stats['legible_frames']/max(1,stats['total_frames'])*100:.1f}%)")
    print(f"Kept frames:    {stats['filtered_frames']}")

    if stats['status_counts']:
        print(f"\n📋 Status breakdown:")
        for status, count in sorted(stats['status_counts'].items()):
            pct = count / stats['total_frames'] * 100
            print(f"   • {status:12s}: {count:4d} ({pct:5.1f}%)")

    # 💡 Quick tip
    leg_ratio = stats['legible_frames'] / max(1, stats['total_frames'])
    if leg_ratio < 0.15:
        print(f"\n💡 Tip: Try lowering threshold to 0.4 for more legible frames")
    elif leg_ratio > 0.6:
        print(f"\n💡 Tip: Try raising threshold to 0.6 for stricter filtering")

    # 🔗 Output paths
    if CONFIG['save_results'] and CONFIG['output_folder']:
        print(f"\n📁 Results saved to: {CONFIG['output_folder']}")

finally:
    pipeline.cleanup()

# 🧪 Optional: Inspect first result
# if stats['tracklet_stats']:
#     first_tracklet = list(stats['tracklet_stats'].keys())[0]
#     print(f"\n🔍 Example: {first_tracklet}")
#     print(f"   Frames: {stats['tracklet_stats'][first_tracklet]['total_frames']}")
#     print(f"   Legible: {stats['tracklet_stats'][first_tracklet]['legible_frames']}")

"""## Step 4: LLM set up
this for now will act as our text reader, from test it is much more accurate than any pre trained and post trained models I found

###4.1 install lib
"""

!pip install -q groq

"""###4.2: Setup of the LLM
- create agent for number recognition and use groq visual to be able to read images
- low temperature agent to avoid overthinking and hallucinations
-**Please input yout personal `GROQ_API_KEY` to work**
"""

# 🤖 Cell: Groq Jersey Number Detection Library
# Run this ONCE at the start of your Colab session
# Then call read_jersey_number() from any other cell

import os
import base64
from groq import Groq

# ============================================================================
# CONFIGURATION
# ============================================================================
# Set GROQ_API_KEY in your shell/environment before running.
os.environ["GROQ_API_KEY"] = os.getenv("GROQ_API_KEY", "")
client = Groq()

# ============================================================================
# FUNCTIONS
# ============================================================================

def encode_image(image_path):
    """Encode image to base64"""
    with open(image_path, "rb") as f:
        return base64.b64encode(f.read()).decode('utf-8')

def read_jersey_number(image_path, model="meta-llama/llama-4-scout-17b-16e-instruct", verbose=True):
    """
    Read jersey number from image using Groq vision

    Args:
        image_path: Path to image file
        model: Groq model to use (default: llama-4-scout)
        verbose: Print debug info

    Returns:
        str: Jersey number or "-1" if not found
    """
    try:
        if not os.path.exists(image_path):
            if verbose:
                print(f"⚠️  File not found: {image_path}")
            return "-1"

        # Encode image
        base64_image = encode_image(image_path)

        # Make API call
        completion = client.chat.completions.create(
            model=model,
            messages=[
                {
                    "role": "user",
                    "content": [
                       {
                          "type": "text",
                          "text": "Look carefully at the player's jersey and identify the jersey number. Return ONLY the number. If uncertain, return your best guess. Only return -1 if it is impossible to read."
                      },
                        {
                            "type": "image_url",
                            "image_url": {
                                "url": f"data:image/jpeg;base64,{base64_image}"
                            }
                        }
                    ]
                }
            ],
            temperature=0.1,
            max_completion_tokens=10,
            top_p=1,
            stream=False,
        )

        # Get result and clean it
        result = completion.choices[0].message.content.strip()

        if verbose:
            print(f"✅ {os.path.basename(image_path)}: {result}")

        return result

    except Exception as e:
        if verbose:
            print(f"❌ Error reading {os.path.basename(image_path)}: {e}")
        return "-1"

def read_jersey_batch(image_paths, model="meta-llama/llama-4-scout-17b-16e-instruct", verbose=True):
    """
    Read jersey numbers from multiple images

    Args:
        image_paths: List of image paths
        model: Groq model to use
        verbose: Print progress

    Returns:
        dict: {image_path: jersey_number}
    """
    results = {}
    for i, img_path in enumerate(image_paths):
        if verbose:
            print(f"[{i+1}/{len(image_paths)}] ", end="")
        number = read_jersey_number(img_path, model=model, verbose=verbose)
        results[img_path] = number
    return results

# ============================================================================
# CONFIRMATION
# ============================================================================
print("✅ Groq Jersey Detection Library Loaded!")
print(f"   • Model: meta-llama/llama-4-scout-17b-16e-instruct")
print(f"   • Functions: read_jersey_number(), read_jersey_batch()")
print(f"   • Example: read_jersey_number('/content/path/to/image.jpg')")

"""---
###4.optional
need to edit your test images make sure to use correct input paths
this simply test your ai ability to read image
"""

#test groq
# 📋 Cell: Test Groq Jersey Detection
# (Run this AFTER the library cell above)


# Or multiple images
test_images = [
    '/content/7_399.jpg',
    '/content/deblurred.png',
]

print("\n📊 Batch Detection:")
results = read_jersey_batch(test_images)
for path, number in results.items():
    print(f"   {path.split('/')[-1]}: {number}")

"""---

## hopeful step5: easy ocr:
**Please ignore the next 3 cells**

1. objective was to use easy ocr to read and detect text on jersey
2. put border on text find dimension-> crop picture to only text
3. augment umage via grayscaling then binary and sharpening augmentation for easier text read

**note** this failed as easyocr has had extrmely low performance at detecting text
- also tested with **Paddle OCr VL** which has higher accuracy on paper and is a newer better ocr model but even it fails at detecting text in a succeful manner
- if curious about paddle ocr please read: https://huggingface.co/PaddlePaddle/PaddleOCR-VL-1.5
"""

!pip install -q easyocr

# 📦 Cell: EasyOCR Jersey Cropper Library
# Run this ONCE at the start of your Colab session
# Then use EasyOCRProcessor() from any other cell

import os, cv2, json, numpy as np
from pathlib import Path
from PIL import Image
import easyocr

# Suppress OpenCV warnings
os.environ['KMP_DUPLICATE_LIB_OK'] = 'TRUE'

# ============================================================================
# CLASS: EasyOCRProcessor
# ============================================================================
class EasyOCRProcessor:
    """Improved EasyOCR cropper with multiple detection strategies for Colab"""

    def __init__(self, pose_folder: str = "out/pose/train", use_gpu: bool = False):
        print("📖 Initializing EasyOCR...")
        self.reader = easyocr.Reader(['en'], gpu=use_gpu, verbose=False)
        self.pose_folder = Path(pose_folder)
        print(f"✓ EasyOCR ready (GPU: {use_gpu})")

    def _get_pose_region(self, image_path: str, tracklet_name: str) -> tuple:
        """Get approximate jersey region from pose keypoints"""
        try:
            pose_file = self.pose_folder / f"{tracklet_name}_pose.json"
            if not pose_file.exists():
                return None
            with open(pose_file, 'r') as f:
                pose_data = json.load(f)
            img_name = Path(image_path).name
            for item in pose_data:
                if Path(item['image']).name == img_name:
                    if not item.get('pose_detected', False):
                        return None
                    keypoints = item.get('keypoints', {})
                    ls, rs, lh, rh = [keypoints.get(k, {}) for k in ['left_shoulder', 'right_shoulder', 'left_hip', 'right_hip']]
                    if not all(k and k.get('x') for k in [ls, rs, lh, rh]):
                        return None
                    x1 = min(ls['x'], rs['x']); x2 = max(ls['x'], rs['x'])
                    y1 = min(ls['y'], rs['y']); y2 = (ls['y'] + rs['y'] + lh['y'] + rh['y']) / 4
                    width, padding_x = x2 - x1, int((x2 - x1) * 0.3)
                    padding_y = int((y2 - y1) * 0.2)
                    return (max(0, int(x1) - padding_x), max(0, int(y1) - padding_y),
                           int(x2) + padding_x, int(y2) + padding_y)
            return None
        except Exception as e:
            return None

    def _crop_from_pose(self, image: np.ndarray, pose_region: tuple) -> np.ndarray:
        x1, y1, x2, y2 = pose_region
        return image[y1:y2, x1:x2]

    def _preprocess_multiple(self, image: np.ndarray) -> list:
        versions = [('original', image)]
        gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
        versions.append(('gray', cv2.cvtColor(gray, cv2.COLOR_GRAY2BGR)))
        clahe = cv2.createCLAHE(clipLimit=3.0, tileGridSize=(8,8))
        versions.append(('clahe', cv2.cvtColor(clahe.apply(gray), cv2.COLOR_GRAY2BGR)))
        _, binary = cv2.threshold(gray, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)
        versions.append(('binary', cv2.cvtColor(binary, cv2.COLOR_GRAY2BGR)))
        return versions

    def _detect_with_fallback(self, image: np.ndarray) -> list:
        best_results = []
        for name, img in self._preprocess_multiple(image):
            for scale in [1.0, 0.75, 0.5]:
                scaled = cv2.resize(img, (int(img.shape[1]*scale), int(img.shape[0]*scale))) if scale < 1.0 else img
                for threshold in [0.3, 0.2, 0.1]:
                    results = self.reader.readtext(scaled, paragraph=False, text_threshold=threshold, low_text=0.2, width_ths=0.7, height_ths=0.7)
                    if results:
                        if scale < 1.0:
                            scaled_results = [(np.array(bbox) / scale, text, conf) for bbox, text, conf in results]
                            best_results.extend(scaled_results)
                        else:
                            best_results.extend(results)
                        if len(best_results) > 5:
                            return best_results
        return best_results

    def _get_tight_bounds(self, all_boxes: np.ndarray, img_shape: tuple) -> tuple:
        if len(all_boxes) == 0:
            return None
        h, w = img_shape[:2]
        x_min, y_min = np.min(all_boxes[:, 0]), np.min(all_boxes[:, 1])
        x_max, y_max = np.max(all_boxes[:, 2]), np.max(all_boxes[:, 3])
        text_width, text_height = x_max - x_min, y_max - y_min
        pad_x, pad_y = max(5, min(20, int(text_width * 0.1))), max(5, min(20, int(text_height * 0.1)))
        return (max(0, int(x_min) - pad_x), max(0, int(y_min) - pad_y),
                min(w, int(x_max) + pad_x), min(h, int(y_max) + pad_y))

    def _heuristic_crop(self, image: np.ndarray) -> tuple:
        gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
        all_regions = []
        edges = cv2.Canny(gray, 30, 100)
        kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (3,3))
        dilated = cv2.dilate(edges, kernel, iterations=2)
        contours, _ = cv2.findContours(dilated, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
        for cnt in contours:
            area = cv2.contourArea(cnt)
            if 100 < area < 5000:
                x, y, w, h = cv2.boundingRect(cnt)
                aspect = w / h
                if 0.3 < aspect < 3.0:
                    all_regions.append([x, y, x+w, y+h])
        if not all_regions:
            h, w = image.shape[:2]
            return (w//3, h//3, 2*w//3, 2*h//3)
        return self._get_tight_bounds(np.array(all_regions), image.shape)

    def _upscale_image(self, image: np.ndarray, scale_factor: int = 10) -> np.ndarray:
        if image is None or image.size == 0:
            return image
        pil_img = Image.fromarray(cv2.cvtColor(image, cv2.COLOR_BGR2RGB))
        new_size = (pil_img.size[0] * scale_factor, pil_img.size[1] * scale_factor)
        upscaled_pil = pil_img.resize(new_size, Image.Resampling.LANCZOS)
        return cv2.cvtColor(np.array(upscaled_pil), cv2.COLOR_RGB2BGR)

    def _crop_edges(self, image: np.ndarray, crop_size: int = 50) -> np.ndarray:
        if image is None or image.size == 0:
            return image
        h, w = image.shape[:2]
        if w <= 2*crop_size or h <= 2*crop_size:
            return image
        return image[crop_size:h-crop_size, crop_size:w-crop_size]

    def detect_and_crop(self, image_path: str, tracklet_name: str = None) -> dict:
        image = cv2.imread(image_path)
        if image is None:
            return {'success': False, 'cropped': None}
        h, w = image.shape[:2]

        # Strategy 1: Pose region
        if tracklet_name:
            pose_region = self._get_pose_region(image_path, tracklet_name)
            if pose_region:
                pose_crop = self._crop_from_pose(image, pose_region)
                results = self._detect_with_fallback(pose_crop)
                if results:
                    x1, y1, x2, y2 = pose_region
                    all_boxes = []
                    for bbox, text, conf in results:
                        pts = np.array(bbox, dtype=np.int32)
                        all_boxes.append([int(pts[:,0].min()) + x1, int(pts[:,1].min()) + y1,
                                         int(pts[:,0].max()) + x1, int(pts[:,1].max()) + y1])
                    if all_boxes:
                        bounds = self._get_tight_bounds(np.array(all_boxes), image.shape)
                        if bounds:
                            x1, y1, x2, y2 = bounds
                            cropped = image[y1:y2, x1:x2]
                            upscaled = self._upscale_image(cropped, 10)
                            final = self._crop_edges(upscaled, 50)
                            return {'success': True, 'cropped': final, 'original': cropped}

        # Strategy 2: Full image
        results = self._detect_with_fallback(image)
        if results:
            all_boxes = []
            for bbox, text, conf in results:
                pts = np.array(bbox, dtype=np.int32)
                all_boxes.append([int(pts[:,0].min()), int(pts[:,1].min()), int(pts[:,0].max()), int(pts[:,1].max())])
            if all_boxes:
                bounds = self._get_tight_bounds(np.array(all_boxes), image.shape)
                if bounds:
                    x1, y1, x2, y2 = bounds
                    cropped = image[y1:y2, x1:x2]
                    upscaled = self._upscale_image(cropped, 10)
                    final = self._crop_edges(upscaled, 50)
                    return {'success': True, 'cropped': final, 'original': cropped}

        # Strategy 3: Heuristic
        bounds = self._heuristic_crop(image)
        if bounds:
            x1, y1, x2, y2 = bounds
            cropped = image[y1:y2, x1:x2]
            upscaled = self._upscale_image(cropped, 10)
            final = self._crop_edges(upscaled, 50)
            return {'success': True, 'cropped': final, 'original': cropped, 'method': 'heuristic'}

        return {'success': False, 'cropped': None}

    def augment(self, cropped: np.ndarray) -> dict:
        if cropped is None or cropped.size == 0:
            return {}
        gray = cv2.cvtColor(cropped, cv2.COLOR_BGR2GRAY)
        versions = {'original': cropped}
        _, binary = cv2.threshold(gray, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)
        versions['binary'] = cv2.cvtColor(binary, cv2.COLOR_GRAY2BGR)
        kernel = np.array([[-1,-1,-1], [-1,9,-1], [-1,-1,-1]])
        sharpened = cv2.filter2D(gray, -1, kernel)
        versions['sharpened'] = cv2.cvtColor(sharpened, cv2.COLOR_GRAY2BGR)
        return versions

    def process(self, image_path: str, tracklet_name: str = None) -> dict:
        result = self.detect_and_crop(image_path, tracklet_name)
        if not result['success']:
            return {'success': False, 'versions': {}}
        versions = self.augment(result['cropped'])
        return {'success': True, 'versions': versions, 'original_cropped': result['original'], 'method': result.get('method', 'easyocr')}

# ============================================================================
# CONFIRMATION
# ============================================================================
print("✅ EasyOCR Jersey Cropper Library Loaded!")
print("   • Class: EasyOCRProcessor")
print("   • Methods: process(), detect_and_crop(), augment()")
print("   • Example:")
print("     processor = EasyOCRProcessor(use_gpu=True)")
print("     result = processor.process('/content/image.jpg', tracklet_name='1000')")
print("     if result['success']: display(result['versions']['original'])")

# 🎯 Simple EasyOCR Text Detection with Border
# Run this cell to detect text/numbers and draw borders around them

import cv2
import numpy as np
from PIL import Image
import easyocr

import os
print("Files in /content:")
print(os.listdir('/content'))

# Initialize EasyOCR (run once)
reader = easyocr.Reader(['en'], gpu=True, verbose=False)
print("✅ EasyOCR loaded")

# Input image path
image_path = '/content/deblurred.png'  # ← Change this!

# Read image
img = cv2.imread(image_path)
img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

# Detect text
results = reader.readtext(img_rgb, paragraph=False, text_threshold=0.3)

# Draw borders around detected text
for bbox, text, conf in results:
    # Convert bbox to integer points
    pts = np.array(bbox, dtype=np.int32)

    # Draw green border around text
    cv2.polylines(img_rgb, [pts], isClosed=True, color=(0, 255, 0), thickness=3)

    # Optional: Add text label above the box
    x_min, y_min = pts[:, 0].min(), pts[:, 1].min()
    cv2.putText(img_rgb, f"{text} ({conf:.2f})",
                (x_min, y_min - 10),
                cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0, 255, 0), 2)

# Display result
print(f"🔍 Found {len(results)} text region(s):")
for bbox, text, conf in results:
    print(f"   • '{text}' (confidence: {conf:.2f})")

display(Image.fromarray(img_rgb))

"""# **Final Main**
the below is final setup into our main cell which runs the entire pipeline

## **Updated step4**:
- reset grow LLM api set up
Copies image to temp folder then auto-cleans when done
**update the `GROQ_API_KEY` with your ke**
"""

# 🤖 Cell: Groq Jersey Number Detection Library (Updated with Temp Cleanup)
# Run this ONCE at the start of your Colab session

import os, base64, shutil, tempfile
from pathlib import Path
from groq import Groq

# ============================================================================
# CONFIGURATION
# ============================================================================
os.environ["GROQ_API_KEY"] = ""
client = Groq()

# Create dedicated temp folder
TEMP_DIR = Path('/content/temp_groq')
TEMP_DIR.mkdir(parents=True, exist_ok=True)

# ============================================================================
# FUNCTIONS
# ============================================================================

def encode_image(image_path):
    """Encode image to base64"""
    with open(image_path, "rb") as f:
        return base64.b64encode(f.read()).decode('utf-8')

def read_jersey_number(image_path, model="meta-llama/llama-4-scout-17b-16e-instruct", verbose=True, cleanup=True):
    """
    Read jersey number from image using Groq vision

    Args:
        image_path: Path to image file
        model: Groq model to use
        verbose: Print debug info
        cleanup: Delete temp file after processing

    Returns:
        str: Jersey number or "-1" if not found
    """
    temp_file = None
    try:
        if not os.path.exists(image_path):
            if verbose:
                print(f"⚠️  File not found: {image_path}")
            return "-1"

        # Copy to temp folder if not already there
        if not str(image_path).startswith('/content/temp'):
            temp_file = TEMP_DIR / f"groq_{Path(image_path).name}"
            shutil.copy2(image_path, temp_file)
            image_path = str(temp_file)

        # Encode image
        base64_image = encode_image(image_path)

        # Make API call
        completion = client.chat.completions.create(
            model=model,
            messages=[
                {
                    "role": "user",
                    "content": [
                        {
                            "type": "text",
                            "text": "What number is on this soccer player's jersey? Return ONLY the number. If you can't read it, return -1."
                        },
                        {
                            "type": "image_url",
                            "image_url": {
                                "url": f"data:image/jpeg;base64,{base64_image}"
                            }
                        }
                    ]
                }
            ],
            temperature=0.1,
            max_completion_tokens=10,
            top_p=1,
            stream=False,
        )

        # Get result and clean it
        result = completion.choices[0].message.content.strip()

        if verbose:
            print(f"✅ {Path(image_path).name}: {result}")

        return result

    except Exception as e:
        if verbose:
            print(f"❌ Error: {e}")
        return "-1"
    finally:
        # Cleanup temp file
        if cleanup and temp_file and temp_file.exists():
            temp_file.unlink()

def read_jersey_batch(image_paths, model="meta-llama/llama-4-scout-17b-16e-instruct", verbose=True):
    """Read jersey numbers from multiple images with progress tracking."""
    results = {}
    for i, img_path in enumerate(image_paths):
        if verbose:
            print(f"[{i+1}/{len(image_paths)}] ", end="")
        number = read_jersey_number(img_path, model=model, verbose=verbose)
        results[img_path] = number
    return results

def cleanup_temp_folder():
    """Delete all files in temp folder."""
    if TEMP_DIR.exists():
        for f in TEMP_DIR.iterdir():
            f.unlink()
        print(f"🧹 Cleaned {len(list(TEMP_DIR.iterdir()))} temp files")

def get_temp_folder_size():
    """Get size of temp folder in MB."""
    if not TEMP_DIR.exists():
        return 0
    total = sum(f.stat().st_size for f in TEMP_DIR.iterdir() if f.is_file())
    return total / (1024 * 1024)

# ============================================================================
# CONFIRMATION
# ============================================================================
print("✅ Groq Jersey Detection Library Loaded!")
print(f"   • Model: meta-llama/llama-4-scout-17b-16e-instruct")
print(f"   • Temp folder: {TEMP_DIR}")
print(f"   • Functions: read_jersey_number(), read_jersey_batch(), cleanup_temp_folder()")
print(f"   • Auto-cleanup: Enabled after each call")

"""## **Updated Step2**:
This cell defines an **image enhancement pipeline** that sequentially applies denoising, deblurring, and super-resolution to improve image quality for better jersey number recognition.

## Pipeline:

### **Core Function: `enhance_with_nafnet_and_sr()`**
Takes an image through four processing stages:

1. **Initial Scaling** (2x) - Resizes image using LANCZOS interpolation
2. **NAFNet Denoise** - Removes noise while preserving details
3. **NAFNet Deblur** - Reduces motion blur and sharpens image  
4. **NAFSSR Super-Resolution** (4x) - Upscales using stereo SR (uses same image for both channels)

### **Key Features:**
- **Temp file management** - Creates intermediate files in `/content/temp_images/`
- **Auto-cleanup** - Removes temporary files after processing (optional)
- **Fallback handling** - Returns original/deblurred image if SR fails
- **Progress tracking** - Verbose mode shows each step's completion

### **Utilities:**
- `cleanup_all_temp_folders()` - Removes all temporary files
- `get_all_temp_size()` - Reports total temp storage usage

This pipeline **progressively enhances** low-quality jersey images before feeding them to the number recognition model, improving accuracy for blurry/noisy/low-res inputs.
"""

# 🔧 Cell: Enhanced Image Processing (NAFNet + NAFSSR Super Resolution)
# Run this AFTER loading NAFNet_dn, NAFNet_db, and NAFSSR models

import os, shutil
from pathlib import Path
from PIL import Image
import cv2

# Create temp folder for image processing
TEMP_IMG_DIR = Path('/content/temp_images')
TEMP_IMG_DIR.mkdir(parents=True, exist_ok=True)

def enhance_with_nafnet_and_sr(image_path: str, tracklet_id: str, frame_id: str,
                                scale_factor: int = 2, sr_factor: int = 4,
                                verbose: bool = True, cleanup: bool = True) -> str:
    """
    Full enhancement pipeline: NAFNet Denoise → Deblur → NAFSSR Super Resolution

    Args:
        image_path: Input image path
        tracklet_id: Tracklet identifier (for temp file naming)
        frame_id: Frame identifier (for temp file naming)
        scale_factor: NAFNet upscale factor (default: 2)
        sr_factor: NAFSSR super resolution factor (default: 4)
        verbose: Print progress
        cleanup: Delete temp files after processing

    Returns:
        str: Path to final enhanced image
    """
    temp_files = []

    try:
        if verbose:
            print(f"   🔧 Enhancing: {Path(image_path).name}")

        # ========== STEP 1: Load and Scale ==========
        img_original = Image.open(image_path)
        new_size = (img_original.width * scale_factor, img_original.height * scale_factor)
        img_input = img_original.resize(new_size, Image.LANCZOS)

        temp_input = TEMP_IMG_DIR / f"{tracklet_id}_{frame_id}_input.png"
        img_input.save(temp_input, 'PNG')
        temp_files.append(temp_input)
        img_input_arr = imread(str(temp_input))

        # ========== STEP 2: NAFNet Denoise ==========
        inp = img2tensor(img_input_arr)
        temp_dn = TEMP_IMG_DIR / f"{tracklet_id}_{frame_id}_dn.png"
        single_image_inference(NAFNet_dn, inp, str(temp_dn))
        temp_files.append(temp_dn)
        img_dn = imread(str(temp_dn))

        if verbose:
            print(f"      ✓ Denoised")

        # ========== STEP 3: NAFNet Deblur ==========
        inp_dn = img2tensor(img_dn)
        temp_db = TEMP_IMG_DIR / f"{tracklet_id}_{frame_id}_db.png"
        single_image_inference(NAFNet_db, inp_dn, str(temp_db))
        temp_files.append(temp_db)
        img_db = imread(str(temp_db))

        if verbose:
            print(f"      ✓ Deblurred")

        # ========== STEP 4: NAFSSR Super Resolution ==========
        # Save deblurred as PNG for NAFSSR
        temp_db_png = TEMP_IMG_DIR / f"{tracklet_id}_{frame_id}_db_png.png"
        Image.fromarray(cv2.cvtColor(img_db, cv2.COLOR_BGR2RGB)).save(str(temp_db_png), 'PNG')
        temp_files.append(temp_db_png)

        # NAFSSR inference (stereo mode, use same image for L/R)
        img_l = imread(str(temp_db_png))
        inp_l = img2tensor(img_l)
        img_r = imread(str(temp_db_png))
        inp_r = img2tensor(img_r)

        temp_sr = TEMP_IMG_DIR / f"{tracklet_id}_{frame_id}_sr.png"
        output_path_pattern = str(TEMP_IMG_DIR / f"{tracklet_id}_{frame_id}_sr_{{}}.png")
        stereo_image_inference(NAFSSR, inp_l, inp_r, output_path_pattern)

        # Load super-resolved image (use L output)
        temp_sr_l = TEMP_IMG_DIR / f"{tracklet_id}_{frame_id}_sr_L.png"
        if temp_sr_l.exists():
            SR_final = imread(str(temp_sr_l))
            temp_files.append(temp_sr_l)
        else:
            # Fallback to deblurred if SR fails
            SR_final = img_db
            if verbose:
                print(f"      ⚠ SR failed, using deblurred")

        if verbose:
            print(f"      ✓ Super-Resolved ({sr_factor}x)")
            print(f"      📐 Size: {img_original.width}x{img_original.height} → {SR_final.shape[1]}x{SR_final.shape[0]}")

        # Save final enhanced image
        final_path = TEMP_IMG_DIR / f"{tracklet_id}_{frame_id}_final.png"
        Image.fromarray(cv2.cvtColor(SR_final, cv2.COLOR_BGR2RGB)).save(str(final_path), 'PNG')

        return str(final_path)

    except Exception as e:
        if verbose:
            print(f"      ❌ Enhancement failed: {e}")
        # Return original path as fallback
        return image_path
    finally:
        # Cleanup temp files
        if cleanup:
            for temp_file in temp_files:
                if temp_file.exists():
                    temp_file.unlink()

def cleanup_all_temp_folders():
    """Delete all temp folders and files."""
    folders = [TEMP_DIR, TEMP_IMG_DIR]
    total_files = 0
    for folder in folders:
        if folder.exists():
            files = list(folder.iterdir())
            for f in files:
                if f.is_file():
                    f.unlink()
                elif f.is_dir():
                    shutil.rmtree(f)
            total_files += len(files)
    print(f"🧹 Cleaned {total_files} temp files from {len(folders)} folders")

def get_all_temp_size():
    """Get total size of all temp folders in MB."""
    total = 0
    for folder in [TEMP_DIR, TEMP_IMG_DIR]:
        if folder.exists():
            for f in folder.iterdir():
                if f.is_file():
                    total += f.stat().st_size
    return total / (1024 * 1024)

# ============================================================================
# CONFIRMATION
# ============================================================================
print("✅ Enhanced Image Processing Library Loaded!")
print(f"   • Temp folder: {TEMP_IMG_DIR}")
print(f"   • Pipeline: NAFNet Denoise → Deblur → NAFSSR Super-Resolution")
print(f"   • Functions: enhance_with_nafnet_and_sr(), cleanup_all_temp_folders()")
print(f"   • Auto-cleanup: Enabled after each enhancement")

"""#Parseq Model

Load and Test
"""

import torch
from PIL import Image
from strhub.data.module import SceneTextDataModule

# Load model
parseq = torch.hub.load('baudm/parseq', 'parseq', pretrained=True).eval()

# Preprocess
img_transform = SceneTextDataModule.get_transform(parseq.hparams.img_size)
img = Image.open("/content/download.png").convert("RGB")
img = img_transform(img).unsqueeze(0)

# Inference
logits = parseq(img)
pred = logits.softmax(-1)

# Decode
label, confidence = parseq.tokenizer.decode(pred)

print("Decoded label:", label[0])

# FIXED confidence
conf_tensor = confidence[0]          # get tensor
conf_score = float(conf_tensor.mean().item())
print("Confidence:", conf_score)

"""#**FINAL MAIN**
This cell runs the **complete end-to-end jersey number recognition pipeline**, combining all previous components (legibility filtering, image enhancement, and Groq LLM) to predict numbers for soccer tracklets.

## **Config Parameters Explained:**

### **Data Settings**
- `split`: Which dataset split to process ('train' or 'test')
- `data_root`: Base directory for SoccerNet data
- `ground_truth_file`: JSON file with true jersey numbers for evaluation
- `output_folder`: Where prediction reports are saved
- `model_path`: Path to legibility classifier model weights

### **Legibility Filtering**
- `legibility_threshold`: Minimum score (0.0-1.0) to consider an image legible (0.85 = 85%)
- `top_k_legible`: Number of best-quality images to select per tracklet (7)
- `backend`: 'auto', 'ml', or 'heuristic' for legibility classification

### **Image Enhancement**
- `nafnet_scale_factor`: Initial upscaling before denoising (2x)
- `nafssr_sr_factor`: Final super-resolution upscaling (4x)

### **Groq LLM**
- `groq_model`: Vision-language model for number reading (LLaMA-4 Scout)

### **Processing**
- `max_tracklets`: Limit number of tracklets to process (25, None = all)
- `verbose`: Print detailed progress
- `save_intermediate`: Whether to save intermediate files
- `auto_cleanup`: Auto-delete temp files to save space

## **Pipeline Flow:**
1. **Initialize** legibility classifier and load ground truth
2. **For each tracklet**:
   - Filter images → keep top-K legible frames
   - Enhance each image (Denoise → Deblur → 4x Super-Resolution)
   - Query Groq LLM for number
3. **Vote** on predictions across frames
4. **Evaluate** against ground truth (accuracy per number, confidence scores)
5. **Save** detailed JSON reports and batch summary
6. **Auto-cleanup** temp files every 10 tracklets
"""

import easyocr

reader = easyocr.Reader(['en'], gpu=True)

def crop_torso(img):
    h, w = img.shape[:2]

    top = int(h * 0.25)
    bottom = int(h * 0.65)
    left = int(w * 0.20)
    right = int(w * 0.80)

    return img[top:bottom, left:right]

import torch
from PIL import Image
from strhub.data.module import SceneTextDataModule

print("🔤 Loading PARSeq...")

parseq = torch.hub.load('baudm/parseq', 'parseq', pretrained=True).eval()

device = "cuda" if torch.cuda.is_available() else "cpu"
parseq = parseq.to(device)

img_transform = SceneTextDataModule.get_transform(parseq.hparams.img_size)

print("✅ PARSeq ready")

def parseq_predict(image_path):
    try:
        img = Image.open(image_path).convert("RGB")
        img = img_transform(img).unsqueeze(0).to(device)

        logits = parseq(img)
        pred = logits.softmax(-1)

        label, confidence = parseq.tokenizer.decode(pred)

        text = label[0]

        # Only accept digits (jersey numbers)
        if not text.isdigit():
            return "-1", 0.0

        conf_tensor = confidence[0]
        conf_score = float(conf_tensor.mean().item())

        return text, conf_score

    except Exception as e:
        print(f"⚠️ PARSeq error: {e}")
        return "-1", 0.0

# 🚀 MAIN PIPELINE: Legibility → NAFNet → NAFSSR → Groq LLM → Tracklet Prediction
# Complete end-to-end with temp file cleanup and super-resolution

import os, json, cv2, numpy as np, shutil
from pathlib import Path
from PIL import Image
from collections import Counter, defaultdict
from datetime import datetime
from tqdm.notebook import tqdm
import torch
from strhub.data.module import SceneTextDataModule

device = "cuda" if torch.cuda.is_available() else "cpu"
parseq = torch.hub.load('baudm/parseq', 'parseq', pretrained=True).eval().to(device)
img_transform = SceneTextDataModule.get_transform(parseq.hparams.img_size)

# ============================================================================
# CONFIGURATION
# ============================================================================
CONFIG = {
    'split': 'test',  # 'train' or 'test'
    'data_root': '/content/soccernet_jersey',
    'ground_truth_file': None,
    'output_folder': '/content/soccernet_jersey/out/predictions',
    'model_path': '/content/soccernet_jersey/models/legibility_resnet34_soccer_20240215.pth',

    # Legibility
    'legibility_threshold': 0.85,
    'top_k_legible': 7,
    'backend': 'auto',

    # Image Enhancement
    'nafnet_scale_factor': 2,      # NAFNet upscale
    'nafssr_sr_factor': 4,         # NAFSSR super-resolution

    # Groq LLM
    'groq_model': 'meta-llama/llama-4-scout-17b-16e-instruct',

    # Processing
    'max_tracklets': 100,
    'verbose': True,
    'save_intermediate': False,
    'auto_cleanup': True,          # Auto-delete temp files
}

# Auto-set paths
if CONFIG['split'] == 'train':
    CONFIG['ground_truth_file'] = '/content/soccernet_jersey/data/train/train_gt.json'
    CONFIG['images_folder'] = '/content/soccernet_jersey/data/train/images'
elif CONFIG['split'] == 'test':
    CONFIG['ground_truth_file'] = '/content/soccernet_jersey/data/test/test_gt.json'
    CONFIG['images_folder'] = '/content/soccernet_jersey/data/test/images'

Path(CONFIG['output_folder']).mkdir(parents=True, exist_ok=True)

# ============================================================================
# HELPER FUNCTIONS
# ============================================================================

def get_legible_images(tracklet_dir: str, pipeline: LegibilityClassifierPipeline,
                       top_k: int = 5, min_score: float = 0.5) -> list:
    """Get top-K most legible images from a tracklet."""
    image_paths = sorted([str(f) for f in Path(tracklet_dir).glob('*.jpg')
                         if f.suffix.lower() in {'.jpg', '.jpeg', '.png'}])

    if not image_paths:
        return []

    scored = []
    for img_path in image_paths:
        result = pipeline.classify_image(img_path)
        if result['legible'] and result['score'] >= min_score:
            scored.append((img_path, result['score']))

    scored.sort(key=lambda x: x[1], reverse=True)
    return [path for path, score in scored[:top_k]]

def predict_tracklet_number(tracklet_dir: str, tracklet_name: str,
                            legibility_pipeline: LegibilityClassifierPipeline) -> dict:
    """Full pipeline with NAFNet + NAFSSR enhancement and auto-cleanup."""
    result = {
        'tracklet_id': tracklet_name,
        'prediction': '-1',
        'confidence': 0.0,
        'legible_count': 0,
        'total_frames': 0,
        'processed_images': [],
        'llm_responses': [],
        'status': 'success',
        'error': None,
        'temp_size_mb': 0
    }

    try:
        # Step 1: Get all images
        image_paths = sorted([str(f) for f in Path(tracklet_dir).glob('*.jpg')])
        result['total_frames'] = len(image_paths)

        if not image_paths:
            result['status'] = 'no_images'
            return result

        # Step 2: Get top-K legible images
        legible_images = get_legible_images(
            tracklet_dir, legibility_pipeline,
            top_k=CONFIG['top_k_legible'],
            min_score=CONFIG['legibility_threshold']
        )
        result['legible_count'] = len(legible_images)

        if CONFIG['verbose']:
            print(f"   📊 {len(legible_images)}/{len(image_paths)} legible")

        if not legible_images:
            result['prediction'] = '-1'
            result['status'] = 'no_legible_images'
            return result

        # Step 3: Enhance + Query Groq for each image
        predictions = []
        for i, img_path in enumerate(legible_images):
            frame_id = Path(img_path).stem

            if CONFIG['verbose']:
                print(f"   🔧 [{i+1}/{len(legible_images)}] {Path(img_path).name}")

            # # Enhance: NAFNet Denoise → Deblur → NAFSSR Super-Resolution
            # enhanced_path = enhance_with_nafnet_and_sr(
            #     img_path,
            #     tracklet_name,
            #     frame_id,
            #     scale_factor=CONFIG['nafnet_scale_factor'],
            #     sr_factor=CONFIG['nafssr_sr_factor'],
            #     verbose=CONFIG['verbose'],
            #     cleanup=CONFIG['auto_cleanup']
            # )

            # # Query Groq LLM

            # # Try OCR first
            # ocr_results = reader.readtext(img)
            # digits = [text for (_, text, conf) in ocr_results if text.isdigit()]

            # if digits:
            #     number = digits[0]
            #     print(f"      🔤 OCR Prediction: {number}")
            # else:
            #     number = read_jersey_number(
            #         enhanced_path,
            #         model=CONFIG['groq_model'],
            #         verbose=False,
            #         cleanup=CONFIG['auto_cleanup']
            #     )
            #     print(f"      🤖 LLM Prediction: {number}")

            # Read the image first
            img = cv2.imread(img_path)

            # Optional: crop torso to increase OCR accuracy
            h, w = img.shape[:2]
            img_crop = img[int(h*0.25):int(h*0.65), int(w*0.2):int(w*0.8)]

            # Enhance the cropped image
            temp_path = f"/tmp/cropped_{tracklet_name}_{frame_id}.jpg"
            cv2.imwrite(temp_path, img_crop)

            enhanced_path = enhance_with_nafnet_and_sr(
                temp_path,
                tracklet_name,
                frame_id,
                scale_factor=CONFIG['nafnet_scale_factor'],
                sr_factor=CONFIG['nafssr_sr_factor'],
                verbose=CONFIG['verbose'],
                cleanup=CONFIG['auto_cleanup']
            )

            # OCR
            ocr_results = reader.readtext(enhanced_path)
            digits = [text for (_, text, conf) in ocr_results if text.isdigit()]
            ocr_number = digits[0] if digits else "-1"

            # PARSeq (always run)
            parseq_number, parseq_conf = parseq_predict(enhanced_path)  # parseq_conf is float 0-1

            # Decide vote weight
            votes = []
            if parseq_number != "-1":
                votes.append((parseq_number, parseq_conf * 2.0))  # Boost PARSeq confidence
            if ocr_number != "-1":
                votes.append((ocr_number, 1.0))  # OCR normal weight

            if votes:
                # Pick the number with the highest weight
                number, conf_score = max(votes, key=lambda x: x[1])
                source = "PARSeq" if number == parseq_number else "OCR"
                print(f"      🔠 {source} Prediction: {number} ({conf_score:.2f})")
            else:
                number = "-1"
                conf_score = 0.0
                print(f"      ❌ No valid prediction")

            predictions.append((number, conf_score))
            result['processed_images'].append({
                'original': img_path,
                'enhanced': enhanced_path,
                'llm_prediction': number,
                'confidence': conf_score
            })
            result['llm_responses'].append(number)

            # Step 4: Weighted voting across all frames
            if predictions:
                weighted_votes = defaultdict(float)
                for num, score in predictions:
                    weighted_votes[num] += score

                final_number, final_score = max(weighted_votes.items(), key=lambda x: x[1])
                total_score = sum(weighted_votes.values())
                result['prediction'] = final_number
                result['confidence'] = final_score / total_score if total_score > 0 else 0.0
                result['vote_distribution'] = dict(weighted_votes)

        # Record temp folder size
        result['temp_size_mb'] = get_all_temp_size()

        return result

    except Exception as e:
        result['status'] = 'error'
        result['error'] = str(e)
        return result

def load_ground_truth(gt_path: str) -> dict:
    """Load ground truth from JSON file."""
    with open(gt_path, 'r') as f:
        gt = json.load(f)
    return {str(k): str(v) for k, v in gt.items()}

def save_report(result: dict, output_folder: str):
    """Save prediction report to JSON file."""
    report_path = Path(output_folder) / f"{result['tracklet_id']}_prediction.json"
    with open(report_path, 'w') as f:
        json.dump(result, f, indent=2, default=str)

def calculate_accuracy(results: list, ground_truth: dict) -> dict:
    """Calculate comprehensive accuracy statistics."""
    stats = {
        'total_tracklets': len(results),
        'successful': 0, 'failed': 0, 'no_legible': 0,
        'correct': 0, 'incorrect': 0,
        'by_number': defaultdict(lambda: {'total': 0, 'correct': 0}),
        'predictions': [], 'confidence_scores': []
    }

    for r in results:
        gt = ground_truth.get(r['tracklet_id'], '-1')
        pred = r['prediction']
        is_correct = (pred == gt)

        stats['by_number'][gt]['total'] += 1
        if is_correct:
            stats['by_number'][gt]['correct'] += 1
            stats['correct'] += 1
        else:
            stats['incorrect'] += 1

        if r['status'] == 'success':
            stats['successful'] += 1
        elif r['status'] == 'no_legible_images':
            stats['no_legible'] += 1
        else:
            stats['failed'] += 1

        if r['confidence'] > 0:
            stats['confidence_scores'].append(r['confidence'])

        stats['predictions'].append({
            'tracklet_id': r['tracklet_id'],
            'ground_truth': gt, 'prediction': pred,
            'correct': is_correct, 'confidence': r['confidence'],
            'status': r['status']
        })

    stats['overall_accuracy'] = stats['correct'] / stats['total_tracklets'] * 100 if stats['total_tracklets'] > 0 else 0

    with_pred = [p for p in stats['predictions'] if p['prediction'] != '-1']
    stats['accuracy_when_predicted'] = (
        sum(1 for p in with_pred if p['correct']) / len(with_pred) * 100
        if with_pred else 0
    )

    stats['coverage'] = len(with_pred) / stats['total_tracklets'] * 100 if stats['total_tracklets'] > 0 else 0

    if stats['confidence_scores']:
        stats['avg_confidence'] = np.mean(stats['confidence_scores']) * 100
        stats['min_confidence'] = min(stats['confidence_scores']) * 100
        stats['max_confidence'] = max(stats['confidence_scores']) * 100

    stats['by_number'] = dict(stats['by_number'])
    return stats

# ============================================================================
# MAIN PIPELINE CLASS
# ============================================================================

class JerseyNumberPipeline:
    def __init__(self, config: dict):
        self.config = config
        self.legibility_pipeline = None
        self.ground_truth = {}

    def initialize(self):
        print(f"\n{'='*70}")
        print(f"🎯 JERSEY NUMBER RECOGNITION PIPELINE (with Super-Resolution)")
        print(f"{'='*70}")
        print(f"Dataset:       {self.config['split']}")
        print(f"Images:        {self.config['images_folder']}")
        print(f"Ground Truth:  {self.config['ground_truth_file']}")
        print(f"Output:        {self.config['output_folder']}")
        print(f"{'='*70}")

        print(f"\n⚙️  Configuration:")
        print(f"   Legibility threshold: {self.config['legibility_threshold']:.2f}")
        print(f"   Top-K legible:        {self.config['top_k_legible']}")
        print(f"   NAFNet scale:         {self.config['nafnet_scale_factor']}x")
        print(f"   NAFSSR super-res:     {self.config['nafssr_sr_factor']}x")
        print(f"   Max tracklets:        {self.config['max_tracklets'] or 'ALL'}")
        print(f"   Auto-cleanup:         {self.config['auto_cleanup']}")
        print(f"{'='*70}\n")

        print(f"🔧 Initializing Legibility Classifier...")
        self.legibility_pipeline = LegibilityClassifierPipeline(
            backend=self.config['backend'],
            model_path=self.config['model_path'],
            threshold=self.config['legibility_threshold'],
            verbose=self.config['verbose']
        )

        print(f"\n📖 Loading Ground Truth...")
        self.ground_truth = load_ground_truth(self.config['ground_truth_file'])
        print(f"   ✓ Loaded {len(self.ground_truth)} tracklets")

        return True

    def run(self):
        if not self.initialize():
            return None

        images_path = Path(self.config['images_folder'])
        tracklets = sorted([d for d in images_path.iterdir() if d.is_dir()])

        if self.config['max_tracklets']:
            tracklets = tracklets[:self.config['max_tracklets']]

        print(f"\n📦 Processing {len(tracklets)} tracklets...\n")

        results = []
        for tracklet in tqdm(tracklets, desc="Overall progress"):
            if self.config['verbose']:
                print(f"\n{'─'*50}")
                print(f"TRACKLET {tracklet.name}")
                print(f"{'─'*50}")

            result = predict_tracklet_number(
                str(tracklet), tracklet.name, self.legibility_pipeline
            )

            gt = self.ground_truth.get(tracklet.name, '-1')
            result['ground_truth'] = gt
            result['correct'] = (result['prediction'] == gt)

            results.append(result)
            save_report(result, self.config['output_folder'])

            if self.config['verbose']:
                status = "✅" if result['correct'] else "❌"
                print(f"   {status} GT: {gt} | Pred: {result['prediction']} | Conf: {result['confidence']*100:.1f}%")

            # Periodic cleanup every 10 tracklets
            if len(results) % 10 == 0 and self.config['auto_cleanup']:
                cleanup_all_temp_folders()

        print(f"\n{'='*70}")
        print(f"📊 CALCULATING ACCURACY")
        print(f"{'='*70}")
        stats = calculate_accuracy(results, self.ground_truth)
        self.print_summary(stats)

        # Save reports
        batch_report = {
            'timestamp': datetime.now().isoformat(),
            'config': self.config,
            'stats': stats,
            'predictions': stats['predictions']
        }

        batch_path = Path(self.config['output_folder']) / 'batch_report.json'
        with open(batch_path, 'w') as f:
            json.dump(batch_report, f, indent=2, default=str)
        print(f"\n💾 Batch report saved: {batch_path}")

        # Final cleanup
        if self.config['auto_cleanup']:
            cleanup_all_temp_folders()

        print(f"\n{'='*70}")
        print(f"✅ PIPELINE COMPLETE")
        print(f"{'='*70}\n")

        return stats

    def print_summary(self, stats: dict):
        print(f"\n📈 ACCURACY SUMMARY")
        print(f"{'─'*50}")
        print(f"Total tracklets:        {stats['total_tracklets']}")
        print(f"Successful:             {stats['successful']}")
        print(f"No legible images:      {stats['no_legible']}")
        print(f"Failed:                 {stats['failed']}")
        print(f"{'─'*50}")
        print(f"Correct predictions:    {stats['correct']}")
        print(f"Incorrect predictions:  {stats['incorrect']}")
        print(f"{'─'*50}")
        print(f"🎯 OVERALL ACCURACY:    {stats['overall_accuracy']:.2f}%")
        print(f"📊 Accuracy (predicted): {stats['accuracy_when_predicted']:.2f}%")
        print(f"📈 Coverage:            {stats['coverage']:.1f}%")
        print(f"{'─'*50}")
        print(f"Confidence:")
        if 'avg_confidence' in stats:
            print(f"   Average: {stats['avg_confidence']:.1f}%")
            print(f"   Min:     {stats['min_confidence']:.1f}%")
            print(f"   Max:     {stats['max_confidence']:.1f}%")
        else:
            print("   No valid confidence scores")

        print(f"\n📋 PER-NUMBER PERFORMANCE")
        print(f"{'─'*50}")
        print(f"Number | Total | Correct | Accuracy")
        print(f"{'─'*50}")
        for num in sorted(stats['by_number'].keys(),
                         key=lambda x: int(x) if x.isdigit() and x != '-1' else float('inf')):
            data = stats['by_number'][num]
            acc = data['correct']/data['total']*100 if data['total'] else 0
            print(f"{num:>6} | {data['total']:5} | {data['correct']:7} | {acc:6.1f}%")
        print(f"{'─'*50}\n")

# ============================================================================
# RUN PIPELINE
# ============================================================================

pipeline = JerseyNumberPipeline(CONFIG)
stats = pipeline.run()

"""---
Ignore this code
This was used to delete any temp png left in the root
"""

# Delete all PNG files in /content that start with "temp"
import os
import glob

# Find all PNG files in /content that start with "temp"
temp_files = glob.glob('/content/temp*.png')

# Print files that will be deleted
if temp_files:
    print(f"Found {len(temp_files)} file(s) to delete:")
    for file in temp_files:
        print(f"  - {os.path.basename(file)}")

    # Delete the files
    for file in temp_files:
        try:
            os.remove(file)
            print(f"Deleted: {os.path.basename(file)}")
        except Exception as e:
            print(f"Error deleting {os.path.basename(file)}: {e}")

    print(f"\n✅ Deleted {len(temp_files)} file(s)")
else:
    print("✅ No files matching '/content/temp*.png' found")